---
name: Jest Testing and Code Coverage

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Jest Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Unit test
        run: npm run ci-test
      
      - name: Write results
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add test-results/test
          git commit -m 'Write test results'
          git push
  
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Code coverage
        run: npm run ci-coverage
      
      - name: Write results
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add test-results/coverage
          git commit -m 'Write code coverage results'
          git push