---
name: Jest Testing and Code Coverage

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Jest Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Unit test
        run: npm run ci-test
      
      - name: Write results
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Writing test results
  
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Code coverage
        run: npm run ci-coverage
      
      - name: Write results
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Writing coverage results