---
name: Jest Testing and Code Coverage

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Unit test
        run: npm run ci-test

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
      
      - name: Code coverage
        run: npm run ci-coverage