---
name: Jest Test and Code Coverage

on:
  push:

jobs:
  test:
    name: Jest Test and Code Coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # Checkout
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Setup CI env for Node
      - run: npm ci

      # Run tests
      - name: Unit test
        run: npm run ci-test
      
      # Run coverage
      - name: Code coverage
        run: npm run ci-coverage
      
      # Push results back into repo
      #- uses: EndBug/add-and-commit@v9
      #  with:
      #    add: 'test-results'

      #- name: Jest Annotations & Coverage
      #  uses: mattallty/jest-github-action@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      #- name: Run tests
      #  uses: ospfranco/gh-jester@v1.0.13
      #  with:
      #    post-comment: true
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      
      - uses: mshick/add-pr-comment@v2
        with:
          message-path: 'test-results/test'

      - uses: mshick/add-pr-comment@v2
        with:
          message-path: 'test-results/coverage'
