---
name: Jest Testing and Code Coverage

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Jest Test and Code Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Unit test
        run: npm run ci-test
      
      - name: Code coverage
        run: npm run ci-coverage
      
      - name: Write results
        run: |
          git config --global user.name 'Tim-404'
          git config --global user.email 'Tim-404@github.com'
          git add test-results
          git commit -m 'Write test results'
          git push
