---
name: Jest Test and Code Coverage

on:
  push:

jobs:
  test:
    name: Jest Test 
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Setup CI env for Node
      - run: |
          npm ci
          mkdir test-results

      # Run tests
      - name: Unit test
        run: npm run ci-test

  # cypress e2e
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Start HTTP server
        run: npx http-server ./ -p 5500 &
        
      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:5500/index.html

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
